#!/bin/bash -x
echo "Welcome User..."

#variables
first_name=""
last_name=""
email=""
pattern=""

function validateName() {
	pattern=^[A-Z]{1}[a-zA-Z]{2,}
	read -p "Enter First Name:" first_name
	read -p "Enter Last Name:" last_name
	if [[ $first_name =~ $pattern ]] && [[ $last_name =~ $pattern ]]
	then
		echo "Name is Valid..."
	else
		echo "Name is Invalid..."
	fi
}

function validateEmail() {
	pattern=^[0-9a-z]+[@][a-z]+[.]{1}[a-z]{2,}$
	read -p "Enter Email Address:" email
	if [[ $email =~ $pattern ]]
	then
		echo "Email Address is Valid..."
	else
		echo "Email Address is Invalid..."
	fi
} 
validateName
validateEmail
