#!/bin/bash -x
echo "Welcome User..."

#variables
firstName=""
lastName=""
email=""
mobileNumber=""
password=""
pattern=""
specialCharacter=0
character=""

function validateName() {
	pattern="^[A-Z]{1}[a-zA-Z]{2,}$"
	read -p "Enter First Name:" firstName
	read -p "Enter Last Name:" lastName
	if [[ $firstName =~ $pattern ]] && [[ $lastName =~ $pattern ]]
	then
		echo "Name is Valid..."
	else
		echo "Name is Invalid..."
	fi
}

function validateEmail() {
	pattern="^[0-9a-z]+[+_.-]?[0-9a-z]+[@][a-z]+[.]{1}[a-z]{2,}[.]?[a-z]+$"
	read -p "Enter Email Address:" email
	if [[ $email =~ $pattern ]]
	then
		echo "Email Address is Valid..."
	else
		echo "Email Address is Invalid..."
	fi
} 

function validateMobileNumber() {
	pattern="^[0-9]{2}[ ][0-9]{10}$"
	read -p "Enter Mobile Number:" mobileNumber
	if [[ $mobileNumber =~ $pattern ]]
	then
		echo "Mobile Number is valid..."
	else
		echo "Mobile Number is Invalid..."
	fi
}

function specialCase() {
	for (( word=0 ; word<${#password} ; word++ ))
   do
      character=${password:$word:1}
      if [[ ! $character == *[[:alnum:]]* ]]
      then
         specialCharacter=$(($specialCharacter + 1))
      fi
   done
}

function validatePassword() {
	pattern="^[0-9A-Za-z]{8,}"
	read -p "Enter Password:" password
	specialCase
	if [ $specialCharacter -eq 1 ]
	then
		echo "Exact 1 special character present..."
	else
		echo "More than 1 special character present..."
	fi
	if [[ $password =~ $pattern ]] && [[ $password == *[[:upper:]]* ]] && [[ $password == *[[:digit:]]* ]] && [ $specialCharacter -eq 1 ]
	then
		echo "Password is valid..."
	else
		echo "Password is Invalid..."
	fi
}

validateName
validateEmail
validateMobileNumber
validatePassword
